### ISSUE TITLE
Different peak numbers (unique peak names) when merging fastq files

### ISSUE THREAD

**Issue by wamber-aww** [kundajelab/atac_dnase_pipelines#97] opened 2018-03-22 15:26 UTC
Thanks for developing this great pipeline! I noticed something with my data

I sequenced my samples twice, once with 100PE and once with 75PE. I did the atac-seq analysis in two different ways:
(1) Merge the fastq files first and then run through the atac_dnase_pipeline
(2) Run individual fastq files and then merge the aligned bam files

After everything ran successfully, I then look at the unique peak names in the $ID_trim.PE2SE.nodup.tn5.pf_peaks.xls file with the following command:
cut -f10 $PEAK_FILE | 'grep ^/home' | sort -u | wc -l
Interestingly, the line counts are different in scenario (1) and (2) -- for some samples, (1) produces more unique names and for others, (2) gives more unique names

I then tested both (1) and (2) but this time with two 50PE sequences. So the only difference is the merged fastq files are all the same length in this situation. Now when I count the unique peak names, (1) and (2) produces the same line counts.

I was wondering:
(a) Does this mean that bowtie2 doesn't deal well with different read lengths (even though I read their manual and it seems like bowtie2 can handle different read lengths) and I should align the fastq files separately and then merge the bam files?
(b) Is counting the unique names in the peak/../peaks.xls file a good indication of the number of peaks or the reproducibility of atac_dnase_pipelines?

Thank you so much!

**Comment by vervacity** [comment] 2018-04-05 19:11
Hi,

It's a little tricky to know exactly, but here's a few thoughts below:
1) An important consideration is that the pipeline removes duplicate reads from the BAM file after alignment. If the FASTQs were merged first, there is a chance that there are two unique fragment events from different libraries that will look like a PCR duplication event (because the fragment happened to be exactly the same, though from different transpositions), and will be removed during de-duplication of reads. As such, to answer your (a) in part, it is best practice to align the fastqs separately and then merge the bam files.
2) From your stated results, there doesn't seem to be a consistent direction of effect (as in, the merged FASTQ -> BAM giving always more peaks than vice versa), so it's hard to know if there's a principle here - but I'll point to some things to check/think about below:
3) Given the different read lengths, it's a little hard to know what piece of this comes from mappability (100PE vs 75PE vs 50PE). Generally ATAC-seq has good mappability (mappability on open chromatin is good with 36bp+, as seen in DNase-seq data), but there may be  slight differences caused by the different read lengths.
4) The ATAC library quality may matter, as well as the number of reads coming from the 100PE or the 75PE set.
5) Adapter trimming may matter as well, in changing the mapping abilities in each case.
6) To answer (b), true reproducibility would be to re-run the pipeline exactly the same way twice and see if the peak counts match up. To get the number of peaks, I would determine which narrowPeak file you'll use (whether the raw MACS2 output, the overlap set, or the IDR) and count those - perhaps something like `zcat {YOUR FILE}.narrowPeak.gz | wc -l`.

Best of luck!

**Closed** 2018-05-29 16:27 UTC
